config/routes.rb
Rails.application.routes.draw do

  get 'add_to_list_from_recipe/show'

  resources :users
  resources :recipes
  resources :products
  resources :list_product_product_recipes
  resources :lists
  resources :product_recipes
  resources :list_products
  resources :recipe_users
  resources :list_users
  resources :branches
  resources :branch_products
  resources :map

  get 'visitors/index'

  get 'sessions/new'

  get 'pages/home'
  
  
  get 'noPreferance' => 'recipes#noPreferance'
  
  
  get 'vegan' => 'recipes#vegan' 
  get 'vegetarian' => 'recipes#vegetarian' 
  get 'diabetic' => 'recipes#diabetic' 
  get 'glutenFree' => 'recipes#glutenFree' 
  get 'nutsAllergy' => 'recipes#nutsAllergy' 
  get 'meatLess' => 'recipes#meatLess' 
  get 'lactoseFree' => 'recipes#lactoseFree' 
  
  

  resources :sessions, only: [:new, :create, :destroy]
  root 'visitors#index'
  get 'list/show' => 'lists#send_email', as: :email_list
  post 'list/show' => 'lists#send_email'
  resources :users do
    get :make_admin, on: :member
  end
  get 'list/show' => 'lists#email'
  
  get 'sessions/new' => 'sessions#new', as: :login
  post 'sessions/new'=> 'sessions#create'
  delete 'visitors/index' => 'sessions#destroy', as: :logout
  get 'users/new' => 'users#new', as: :signup
  get 'products/' => 'products#index', as: :productpage
  get 'list_products/' => 'list_products#index', as: :grocerypage
  post 'users/new' => 'users#new'
  post 'products/new' => 'products#new'
  post 'recipes/new' => 'recipes#new'
  post 'lists/new' => 'lists#new'
  get 'lists/add_item' => 'lists#add_item', as: :addgrocery
  resources :add_to_list do 
    post '/add_to_list/:product_id/:list_id' => 'list#add_to_list' 
    get '/add_to_list/:product_id/:list_id' => 'list#add_to_list'
  end
  resources :send_list do 
    post '/send_list/:user_id' => 'send_list#show' 
    get '/send_list/:user_id' => 'send_list#show'
  end
  resources :add_to_recipe do 
    post '/add_to_recipe/:product_id/:recipe_id' => 'add_to_recipe#show' 
    get '/add_to_recipe/:product_id/:recipe_id' => 'add_to_recipe#show'
  end
  resources :add_to_list_from_recipe do 
    post '/add_to_list_from_recipe/:product_id/:list_id/:recipe_id' => 'add_to_list_from_recipe#show' 
    get '/add_to_list_from_recipe/:product_id/:list_id/:recipe_id' => 'add_to_list_from_recipe#show' 
  end
  resources :share_list do 
    post '/share_list/:user_id/:list_id' => 'share_list#show' 
    get '/share_list/:user_id/:list_id' => 'share_list#show' 
  end
  
  resources :remove_from_list do 
    post '/remove_from_list/:product_id/:list_id' => 'remove_from_list#show' 
    get '/remove_from_list/:product_id/:list_id' => 'remove_from_list#show' 
  end
  
  post 'lists/save' => 'lists#screenshot'

end

app/models/availability.rb
class Availability < ActiveRecord::Base
    belongs_to :product
    belongs_to :branch
end

app/models/branch.rb
class Branch < ApplicationRecord
	has_many :branch_products
	has_many :products, :through => :branch_products
end

app/models/branch_product.rb
class BranchProduct < ApplicationRecord
	belongs_to :product
	belongs_to :branch

end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
    belongs_to :user
    belongs_to :list
end

app/models/custom_recipe.rb
class CustomRecipe < ActiveRecord::Base
    belongs_to :user
    belongs_to :recipe
end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
    belongs_to :product
    belongs_to :list
    
    has_many :list_product_recipes
    has_many :ingredients, :through => :list_product_recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
    belongs_to :recipe
    belongs_to :product
    
    has_many :list_product_recipes
    has_many :groceries, :through => :list_product_recipes
end

app/models/list.rb
class List < ApplicationRecord
	has_many :list_users
	has_many :users, :through => :list_users
    
    has_many :list_products
    has_many :products, :through => :list_products
end

app/models/list_product.rb
class ListProduct < ApplicationRecord
	belongs_to :product
	belongs_to :list

	has_many :list_product_product_recipes
    has_many :product_recipes, :through => :list_product_product_recipes
end

app/models/list_user.rb
class ListUser < ApplicationRecord
	belongs_to :user
	belongs_to :list

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :branch_products
	has_many :branches, :through => :branch_products
    
    has_many :list_products
    has_many :lists, :through => :list_products
    
    has_many :product_recipes
    has_many :recipes, :through => :product_recipes
end

app/models/product_recipe.rb
class ProductRecipe < ApplicationRecord
	belongs_to :recipe
	belongs_to :product

	has_many :list_product_product_recipes
    has_many :list_products, :through => :list_product_product_recipes

end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :recipe_users
	has_many :users, :through => :recipe_users
    
    has_many :product_recipes
    has_many :products, :through => :product_recipes
    
    
    scope :noPreferance, -> { where(dietaryreqs: 'None') }
    scope :vegan, -> { where(dietaryreqs: 'Vegan') }
    scope :vegetarian, -> { where(dietaryreqs: 'Vegetarian') }
    scope :diabetic, -> { where(dietaryreqs: 'Diabetic') }
    scope :glutenFree, -> { where(dietaryreqs: 'Gluten Free') }
    scope :nutsAllergy, -> { where(dietaryreqs: 'Nuts allergy') }
    scope :meatLess, -> { where(dietaryreqs: 'Meat less') }
    scope :lactoseFree, -> { where(dietaryreqs: 'Lactose free') }
    


end

app/models/recipe_user.rb
class RecipeUser < ApplicationRecord
	belongs_to :user
	belongs_to :recipe

end

app/models/user.rb
class User < ApplicationRecord
	has_many :list_users
	has_many :lists, :through => :list_users
    
    has_many :recipe_users
    has_many :recipes, :through => :recipe_users
    
    def self.search(search)
      where("firstname LIKE ?", "%#{search}%")
    end
    
    
    validates :firstname, presence: true, length: { maximum: 50 }
    validates :lastname, presence: true
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :password, :password_confirmation, presence: true, length: { minimum: 6 }
    
    before_save { self.email = email.downcase }

	has_secure_password
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :admin_only
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:name, :location, :map)
    end
    
    def admin_only
      if !current_user.admin?
        redirect_to root_path
      end
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/branches/_form.html.erb
<%= form_with(model: branch, local: true) do |form| %>
  <% if branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% branch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Branch Name" %><br>
    <%= form.text_field :name, id: :branch_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :location %><br>
    <%= form.text_field :location, id: :branch_location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :map %><br>
    <%= form.text_area :map, id: :branch_map, class: "form-control" %>
  </div>

  <div class="form-actions">
    <%= form.submit :class => 'btn btn-primary text-uppercase' %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing Branch</h1>

<%= render 'form', branch: @branch %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>
<%= render 'layouts/footer' %>

app/views/branches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Branches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Map</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.location %></td>
        <td><%= branch.map %></td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Branch', new_branch_path %>
<%= render 'layouts/footer' %>

app/views/branches/new.html.erb
<h1>New Branch</h1>

<%= render 'form', branch: @branch %>

<%= link_to 'Back', branches_path, class: 'btn btn-primary text-uppercase' %>
<%= render 'layouts/footer' %>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @branch.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @branch.location %>
</p>

<p>
  <strong>Map:</strong>
  <%= @branch.map %>
</p>

<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>
<%= render 'layouts/footer' %>