config/routes.rb
Rails.application.routes.draw do

  get 'add_to_list_from_recipe/show'

  resources :users
  resources :recipes
  resources :products
  resources :list_product_product_recipes
  resources :lists
  resources :product_recipes
  resources :list_products
  resources :recipe_users
  resources :list_users
  resources :branches
  resources :branch_products
  resources :map

  get 'visitors/index'

  get 'sessions/new'

  get 'pages/home'
  
  
  get 'noPreferance' => 'recipes#noPreferance'
  
  
  get 'vegan' => 'recipes#vegan' 
  get 'vegetarian' => 'recipes#vegetarian' 
  get 'diabetic' => 'recipes#diabetic' 
  get 'glutenFree' => 'recipes#glutenFree' 
  get 'nutsAllergy' => 'recipes#nutsAllergy' 
  get 'meatLess' => 'recipes#meatLess' 
  get 'lactoseFree' => 'recipes#lactoseFree' 
  
  

  resources :sessions, only: [:new, :create, :destroy]
  root 'visitors#index'
  get 'list/show' => 'lists#send_email', as: :email_list
  post 'list/show' => 'lists#send_email'
  resources :users do
    get :make_admin, on: :member
  end
  get 'list/show' => 'lists#email'
  
  get 'sessions/new' => 'sessions#new', as: :login
  post 'sessions/new'=> 'sessions#create'
  delete 'visitors/index' => 'sessions#destroy', as: :logout
  get 'users/new' => 'users#new', as: :signup
  get 'products/' => 'products#index', as: :productpage
  get 'list_products/' => 'list_products#index', as: :grocerypage
  post 'users/new' => 'users#new'
  post 'products/new' => 'products#new'
  post 'recipes/new' => 'recipes#new'
  post 'lists/new' => 'lists#new'
  get 'lists/add_item' => 'lists#add_item', as: :addgrocery
  resources :add_to_list do 
    post '/add_to_list/:product_id/:list_id' => 'list#add_to_list' 
    get '/add_to_list/:product_id/:list_id' => 'list#add_to_list'
  end
  resources :send_list do 
    post '/send_list/:user_id' => 'send_list#show' 
    get '/send_list/:user_id' => 'send_list#show'
  end
  resources :add_to_recipe do 
    post '/add_to_recipe/:product_id/:recipe_id' => 'add_to_recipe#show' 
    get '/add_to_recipe/:product_id/:recipe_id' => 'add_to_recipe#show'
  end
  resources :add_to_list_from_recipe do 
    post '/add_to_list_from_recipe/:product_id/:list_id/:recipe_id' => 'add_to_list_from_recipe#show' 
    get '/add_to_list_from_recipe/:product_id/:list_id/:recipe_id' => 'add_to_list_from_recipe#show' 
  end
  resources :share_list do 
    post '/share_list/:user_id/:list_id' => 'share_list#show' 
    get '/share_list/:user_id/:list_id' => 'share_list#show' 
  end
  
  resources :remove_from_list do 
    post '/remove_from_list/:product_id/:list_id' => 'remove_from_list#show' 
    get '/remove_from_list/:product_id/:list_id' => 'remove_from_list#show' 
  end
  
  post 'lists/save' => 'lists#screenshot'

end

app/models/list_product_product_recipe.rb
class ListProductProductRecipe < ApplicationRecord
	belongs_to :product_recipe
	belongs_to :list_product

end

app/controllers/list_product_product_recipes_controller.rb
class ListProductProductRecipesController < ApplicationController
  before_action :set_list_product_product_recipe, only: [:show, :edit, :update, :destroy]

  # GET /list_product_product_recipes
  # GET /list_product_product_recipes.json
  def index
    @list_product_product_recipes = ListProductProductRecipe.all
  end

  # GET /list_product_product_recipes/1
  # GET /list_product_product_recipes/1.json
  def show
  end

  # GET /list_product_product_recipes/new
  def new
    @list_product_product_recipe = ListProductProductRecipe.new
  end

  # GET /list_product_product_recipes/1/edit
  def edit
  end

  # POST /list_product_product_recipes
  # POST /list_product_product_recipes.json
  def create
    @list_product_product_recipe = ListProductProductRecipe.new(list_product_product_recipe_params)

    respond_to do |format|
      if @list_product_product_recipe.save
        format.html { redirect_to @list_product_product_recipe, notice: 'List product product recipe was successfully created.' }
        format.json { render :show, status: :created, location: @list_product_product_recipe }
      else
        format.html { render :new }
        format.json { render json: @list_product_product_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_product_product_recipes/1
  # PATCH/PUT /list_product_product_recipes/1.json
  def update
    respond_to do |format|
      if @list_product_product_recipe.update(list_product_product_recipe_params)
        format.html { redirect_to @list_product_product_recipe, notice: 'List product product recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_product_product_recipe }
      else
        format.html { render :edit }
        format.json { render json: @list_product_product_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_product_product_recipes/1
  # DELETE /list_product_product_recipes/1.json
  def destroy
    @list_product_product_recipe.destroy
    respond_to do |format|
      format.html { redirect_to list_product_product_recipes_url, notice: 'List product product recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_product_product_recipe
      @list_product_product_recipe = ListProductProductRecipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_product_product_recipe_params
      params.require(:list_product_product_recipe).permit(:list_product_id, :product_recipe_id)
    end
end

app/helpers/list_product_product_recipes_helper.rb
module ListProductProductRecipesHelper
end

app/views/list_product_product_recipes/_form.html.erb
<%= form_with(model: list_product_product_recipe, local: true) do |form| %>
  <% if list_product_product_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list_product_product_recipe.errors.count, "error") %> prohibited this list_product_product_recipe from being saved:</h2>

      <ul>
      <% list_product_product_recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :list_product_id %>
    <%= form.number_field :list_product_id, id: :list_product_product_recipe_list_product_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :product_recipe_id %>
    <%= form.number_field :product_recipe_id, id: :list_product_product_recipe_product_recipe_id, class: "form-control" %>
  </div>

  <div class="form-actions">
    <%= form.submit :class => 'btn btn-primary text-uppercase' %>
  </div>
<% end %>

app/views/list_product_product_recipes/edit.html.erb
<h1>Editing List Product Product Recipe</h1>

<%= render 'form', list_product_product_recipe: @list_product_product_recipe %>

<%= link_to 'Show', @list_product_product_recipe %> |
<%= link_to 'Back', list_product_product_recipes_path %>
<%= render 'layouts/footer' %>

app/views/list_product_product_recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List Product Product Recipes</h1>

<table>
  <thead>
    <tr>
      <th>List product</th>
      <th>Product recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @list_product_product_recipes.each do |list_product_product_recipe| %>
      <tr>
        <td><%= list_product_product_recipe.list_product_id %></td>
        <td><%= list_product_product_recipe.product_recipe_id %></td>
        <td><%= link_to 'Show', list_product_product_recipe %></td>
        <td><%= link_to 'Edit', edit_list_product_product_recipe_path(list_product_product_recipe) %></td>
        <td><%= link_to 'Destroy', list_product_product_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List Product Product Recipe', new_list_product_product_recipe_path %>
<%= render 'layouts/footer' %>

app/views/list_product_product_recipes/new.html.erb
<h1>New List Product Product Recipe</h1>

<%= render 'form', list_product_product_recipe: @list_product_product_recipe %>

<%= link_to 'Back', list_product_product_recipes_path, class: 'btn btn-primary text-uppercase' %>
<%= render 'layouts/footer' %>

app/views/list_product_product_recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List product:</strong>
  <%= @list_product_product_recipe.list_product_id %>
</p>

<p>
  <strong>Product recipe:</strong>
  <%= @list_product_product_recipe.product_recipe_id %>
</p>

<%= link_to 'Edit', edit_list_product_product_recipe_path(@list_product_product_recipe) %> |
<%= link_to 'Back', list_product_product_recipes_path %>
<%= render 'layouts/footer' %>